# Generated by Django 2.1 on 2019-03-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products_name', models.CharField(max_length=255)),
                ('products_price', models.FloatField()),
                ('products_stock', models.IntegerField()),
                ('products_urls', models.CharField(max_length=2055)),
            ],
        ),
    ]
